# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Digital eye candy', max_length=100),
        ),
    ]
