# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
