# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20190318_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
