# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_auto_20190318_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
