# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0011_auto_20190318_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='project_pics/default.jpeg', upload_to=''),
        ),
    ]
